<?php

/**
 * Utilitário para analisar e extrair as informações sobre as linhas
 * de ônibus que passam nos endereços. 
 */

// Carrega o Simple HTML DOM parser
require_once "../vendor/simple_html_dom.php";

/**
 * Listas de endereços por tipo
 */

$AvArray = array(
    array('AV ADALBERTO SIMÃO NADER','0123'),
    array('AV ADELPHO POLI MONJARDIM','718 '),
    array('AV ALBERTO TORRES','0180'),
    array('AV ALEXANDRE BUAIZ','0134'),
    array('AV ALZIRO ZARUR','0200'),
    array('AV AMÉRICO BUAIZ','418 '),
    array('AV ANÍSIO FERNANDES COELHO','0208'),
    array('AV ANTÔNIO BORGES','652 '),
    array('AV ARMANDO DUARTE RABELO','2425'),
    array('AV BRASIL','0318'),
    array('AV CAPITÃO JOÃO BRANDÃO','0361'),
    array('AV CARLOS GOMES DE SÁ','814 '),
    array('AV CARLOS MOREIRA LIMA','0048'),
    array('AV CEZAR HILAL','0197'),
    array('AV CLETO NUNES','0145'),
    array('AV COMISSÁRIO OTÁVIO QUEIROZ','0253'),
    array('AV CONSTANTINO DAVID TEIXEIRA','711 '),
    array('AV CONSTRUTOR DAVID TEIXEIRA','0250'),
    array('AV CORONEL JOSE MARTINS DE FIGUEIREDO','387 '),
    array('AV DANTE MICHELINI','0238'),
    array('AV DÁRIO LOURENÇO DE SOUZA','0100'),
    array('AV DESEMBARGADOR SANTOS NEVES','0172'),
    array('AV DOS EXPEDICIONÁRIOS','0245'),
    array('AV DUARTE LEMOS','0147'),
    array('AV ELIAS  MIGUEL','0135'),
    array('AV ENGENHEIRO CHARLES BITRAN','693 '),
    array('AV EUGÊNIO PACHECO DE QUEIROZ','694 '),
    array('AV FERNANDO FERRARI','0198'),
    array('AV FRANCISCO GENEROSO DA FONSECA','0204'),
    array('AV GETÚLIO VARGAS','0107'),
    array('AV GOVERNADOR BLEY','0150'),
    array('AV GOVERNADOR EURICO REZENDE','696 '),
    array('AV GOVERNADOR JOSÉ SETTE','0144'),
    array('AV GUILHERME BASSINI','0151'),
    array('AV HUGO VIOLA','0201'),
    array('AV ISAAC LOPES DE RUBIM','692 '),
    array('AV JAIR ETIENNE DESSAUNE','333 '),
    array('AV JERÔNIMO MONTEIRO','0105'),
    array('AV JERÔNIMO VERVLOET','0289'),
    array('AV JOÃO SANTOS FILHO','659 '),
    array('AV JONES SANTOS NEVES','909 '),
    array('AV JOSÉ CASSIANO DOS SANTOS','614 '),
    array('AV JOSÉ MIRANDA MACHADO','656 '),
    array('AV JOSÉ NEVES CYPRESTES','680 '),
    array('AV JOUBERT DE BARROS','0054'),
    array('AV LEITÃO DA SILVA','0138'),
    array('AV MANOEL MARQUES','0273'),
    array('AV MANOEL NUNES DO AMARAL PEREIRA','661 '),
    array('AV MARCOS DE AZEVEDO','0146'),
    array('AV MARECHAL CAMPOS','0137'),
    array('AV MARECHAL MASCARENHAS DE MORAES','0142'),
    array('AV MARUÍPE','0160'),
    array('AV MUNIR HILAL','662 '),
    array('AV NAIR AZEVEDO SILVA','0216'),
    array('AV NOSSA SENHORA DA PENHA','0170'),
    array('AV NOSSA SENHORA DOS NAVEGANTES','0173'),
    array('AV PAULINO MÜLLER','0083'),
    array('AV PEDRO DEPIANTE','0121'),
    array('AV PEDRO FEU ROSA','0210'),
    array('AV PRES. FLORENTINO AVIDOS','0291'),
    array('AV PRESIDENTE COSTA E SILVA','0303'),
    array('AV PRESIDENTE FLORENTINO AVIDOS','1227'),
    array('AV PRINCESA ISABEL','0106'),
    array('AV PROF HERMÍNIO BLACKMAN','0065'),
    array('AV PROFESSOR FERNANDO DUARTE RABELO','0384'),
    array('AV QUATRO DE SETEMBRO','0152'),
    array('AV REPÚBLICA','0109'),
    array('AV RIO BRANCO','0308'),
    array('AV ROBERTO EWALD','2512'),
    array('AV ROZENDO SERAPIÃO DE SOUZA FILHO','908 '),
    array('AV SANTO ANTÔNIO','0132'),
    array('AV SANTO ANTONIO.','415 '),
    array('AV SATURNINO DE BRITO','0237'),
    array('AV SATURNINO RANGEL MAURO','0256'),
    array('AV SOLON BORGES','0298'),
    array('AV VITÓRIA','0136'),
    array('AV. FERNANDO DUARTE RABELO','655 '),
    array('AVENIDA ROBERT KENNEDY','1516')
);
$PcArray = array(
    array('PRAÇA AMÉRICO POLI MONJARDIM','683 '),
    array('PRAÇA ANÍBAL ANTHERO MARTINS','0211'),
    array('PRAÇA ANTÔNIO FERREIRA MARQUES','0183'),
    array('PRAÇA ANTÔNIO TRAJANO SANTOS','0195'),
    array('PRAÇA ARISTÓBULO INOCÊNCIO FERREIRA','653 '),
    array('PRAÇA BENEDITO RODRIGUES CRUZ','0251'),
    array('PRAÇA CAETANO BASSANI','101 '),
    array('PRAÇA CAETANO BASSINI','624 '),
    array('PRAÇA CORONEL FRANCISCO P. DO NASCIMENTO','812 '),
    array('PRAÇA COSTA PEREIRA','0334'),
    array('PRAÇA CRISTÓVÃO JACQUES','0221'),
    array('PRAÇA DA AV. BEIRA MAR','628 '),
    array('PRAÇA DA BANDEIRA','817 '),
    array('PRAÇA DE GOIABEIRAS','602 '),
    array('PRAÇA DO AEROPORTO','0293'),
    array('PRAÇA DOS DESEJOS','525 '),
    array('PRAÇA DR.CARLITO L. VON SCHILGEN','809 '),
    array('PRAÇA FLAVIO MÁRIO FAUSTINI','0012'),
    array('PRAÇA FRANCISCO P NASCIMENTO','0290'),
    array('PRAÇA GILBERTO MENDONÇA PAIVA','0126'),
    array('PRAÇA IRMÃ JOSEPHA HOSANAH','187 '),
    array('PRAÇA MISAEL PENA','0387'),
    array('PRAÇA PHILOGOMIRO LANNES','0207'),
    array('PRAÇA REGINA FRIGERI FURNO','0205'),
    array('PRAÇA UBALDO REMALHETE MAIA','578 '),
    array('PRAÇA VICENTE GUIDA','0215'),
    array('PRAÇA WOLGHANO NETTO','0254')
);
$RuaArray = array(
    array('RUA  DOUTOR BENJAMIM COSTA','2788'),
    array('RUA ADALFREDO WANICK','811 '),
    array('RUA ADOLPHO CASSOLI','0167'),
    array('RUA ADRIANO FONTANA','0008'),
    array('RUA AFONSO CLÁUDIO','0325'),
    array('RUA AFONSO SARLO','0177'),
    array('RUA AGUIAR FILHO','255 '),
    array('RUA ALAOR DE QUEIROZ ARAUJO','0382'),
    array('RUA ALAOR QUEIROZ DE ARAÚJO','0223'),
    array('RUA ALARICO DE LIMA CABRAL','0030'),
    array('RUA ALCINO PEREIRA FLORES','400 '),
    array('RUA ALCINO PEREIRA NETO','0242'),
    array('RUA ALDA MARIA LYRA VICENTINI','684 '),
    array('RUA ALDOMÁRIO SOARES PINTO','698 '),
    array('RUA ALEIXO NETTO','0279'),
    array('RUA ALFREDO BLACKMAN','0004'),
    array('RUA ALLAN KARDEC','0070'),
    array('RUA ALMIRANTE SOÍDO','0222'),
    array('RUA ALMIRANTE TAMANDARÉ','0227'),
    array('RUA ALUYSIO SIMÕES','0056'),
    array('RUA ALVIM SOARES BERMUDES','2513'),
    array('RUA ALVIMAR SILVA','715 '),
    array('RUA ALZIRO VIANA','504 '),
    array('RUA ALZIRO ZARUR','0015'),
    array('RUA AMÉLIA CUNHA ORNELAS','0053'),
    array('RUA AMENÓPHIS DE ASSIS','8521'),
    array('RUA AMÉRICA DO SUL','0320'),
    array('RUA ÂNGELO ZARDINI','0310'),
    array('RUA ANNIBAL VIEIRA RABAYOLLI','806 '),
    array('RUA ANTENOR GUIMARÃES','0700'),
    array('RUA ANTÔNIO ALVES BATISTA ','687 '),
    array('RUA ANTÔNIO CAMPOS','0129'),
    array('RUA ANTÔNIO NOBRE FILHO','0296'),
    array('RUA ANTÔNIO PINTO DE QUEIROZ','297 '),
    array('RUA ANTÔNIO RIBEIRO','704 '),
    array('RUA ANTÔNIO SALOMÃO FILHO','688 '),
    array('RUA ANTÔNIO SANTOS','0220'),
    array('RUA ARCHIMINO MATTOS','0252'),
    array('RUA ARIOSTO DA SILVA SANTOS','0228'),
    array('RUA ARIOVALDO FAVALESSA','519 '),
    array('RUA ARISTEU AGUIAR','0143'),
    array('RUA ARISTIDES NAVARRO','0354'),
    array('RUA ARISTÓBULO  BARBOSA LEÃO','0202'),
    array('RUA ARLINDO BRÁS DO NASCIMENTO','702 '),
    array('RUA ARLINDO SODRÉ','099 '),
    array('RUA ARMANDO MOREIRA DE OLIVEIRA','810 '),
    array('RUA ATALIDES MOREIRA DE SOUZA','874 '),
    array('RUA ATTÍLIO SPERANDIO','0155'),
    array('RUA AUGUSTO AYRES RIBEIRO','721 '),
    array('RUA AUGUSTO EMÍLIO ESTELITA LINS','0241'),
    array('RUA AUGUSTO RONCETTI','0154'),
    array('RUA AUGUSTO TEIXEIRA','714 '),
    array('RUA AVANDIR OLIVEIRA DA SILVA ','707 '),
    array('RUA AYRTON SENNA','2654'),
    array('RUA BALBINA DOS SANTOS','0398'),
    array('RUA BARÃO DE ITAPEMIRIM','0104'),
    array('RUA BARÃO DE MAUÁ','5423'),
    array('RUA BELA VISTA','719 '),
    array('RUA BELMIRO TEIXEIRA PIMENTA','0267'),
    array('RUA BENEDITO BARCELOS','0347'),
    array('RUA BENEDITO MUNIZ','677 '),
    array('RUA BERESFORD MARTINS MOREIRA','673 '),
    array('RUA BOA ESPERANÇA','409 '),
    array('RUA BOA VISTA','0116'),
    array('RUA BOULEVARD ANTILHAS','0265'),
    array('RUA BOULEVARD CARAÍBAS','0246'),
    array('RUA BOULEVARD MEDITERRANEO','613 '),
    array('RUA BRÁS RUBIM','0009'),
    array('RUA BYRON VIDIGAL','0261'),
    array('RUA CABO JOÃO FELIX AMORIM','1224'),
    array('RUA CAETANO JOSÉ GOMES','0153'),
    array('RUA CAIS SÃO FRANCISCO','0340'),
    array('RUA CANOEIROS','720 '),
    array('RUA CAPITÃO DOMINGOS CORRÊIA ROCHA','805 '),
    array('RUA CAPITÃO FEU','0299'),
    array('RUA CAPITÃO JOÃO BRANDÃO','903 '),
    array('RUA CARAMURU','0339'),
    array('RUA CARLOS E MONT LEMOS','390 '),
    array('RUA CARLOS EDUARDO MONTEIRO DE LEMOS','047 '),
    array('RUA CARLOS MARTINS','0239'),
    array('RUA CARLOS MOREIRA LIMA','513 '),
    array('RUA CASTELO','501 '),
    array('RUA CELSO CALMON','0022'),
    array('RUA CEREJEIRAS','0620'),
    array('RUA CHAFIC MURAD','0049'),
    array('RUA CINCO','530 '),
    array('RUA CIRO LOPES PEREIRA','603 '),
    array('RUA CIRO VIEIRA DA CUNHA','0294'),
    array('RUA CLÓVIS MACHADO','0225'),
    array('RUA COLATINO BARROSO','0098'),
    array('RUA CONSELHEIRO MAFRA','1515'),
    array('RUA CONSTANTE SODRÉ','301 '),
    array('RUA CONSTANTINI CAMILO GIANORDOLI','510 '),
    array('RUA CONSTANTINO FURLANE','0187'),
    array('RUA CORONEL ALZIRO VIANNA','2929'),
    array('RUA CORONEL ETIENNE DESSAUNE','664 '),
    array('RUA CORONEL JOSÉ MARTINS FIGUEIREDO','0166'),
    array('RUA CORONEL MONJARDIM','0342'),
    array('RUA CORONEL SCHWAB FILHO','8520'),
    array('RUA CORONOL ALZIRO VIANNA','906 '),
    array('RUA COUTINHO MASCARENHAS','0355'),
    array('RUA DA CONSTITUINTE ','658 '),
    array('RUA DA CORAGEM','0234'),
    array('RUA DA CRECHE','0255'),
    array('RUA DA ESTIVA','385 '),
    array('RUA DA GALERIA','800 '),
    array('RUA DA GRÉCIA','0278'),
    array('RUA DA LIBERDADE','0161'),
    array('RUA DA LUTA','0317'),
    array('RUA DA SAUDADE','0284'),
    array('RUA DANIEL ABREU MACHADO','0140'),
    array('RUA DARCY GRIJÓ','0199'),
    array('RUA DAS OLIVEIRAS','619 '),
    array('RUA DAS PALMEIRAS','0139'),
    array('RUA DELZINO CORREA','0407'),
    array('RUA DEPUTADO CASTELLO MENDONÇA','907 '),
    array('RUA DEPUTADO DARCY CASTELO MENDONÇA','0122'),
    array('RUA DERMIVAL LYRIO ','654 '),
    array('RUA DES ERNESTO DA SILVA GUIMARÃES','617 '),
    array('RUA DESEMBARGADOR DEMERVAL LYRIO','0249'),
    array('RUA DESEMBARGADOR FERREIRA COELHO','902 '),
    array('RUA DESEMBARGADOR GILSON MENDONÇA','0112'),
    array('RUA DESEMBARGADOR JOÃO MANOEL CARVALHO','605 '),
    array('RUA DEZENOVE DE MAIO','0181'),
    array('RUA DIONÍSIO ROSENDO','0352'),
    array('RUA DO CAJÚ','539 '),
    array('RUA DO CANAL','0345'),
    array('RUA DO CANAVIAL','0248'),
    array('RUA DO COQUEIRO','0159'),
    array('RUA DO LUAR','676 '),
    array('RUA DOM BENEDITO','0094'),
    array('RUA DOM FERNANDO','0331'),
    array('RUA DOM PEDRO II','0085'),
    array('RUA DONA MARIA ROSA','0018'),
    array('RUA DOS CANOEIROS','0027'),
    array('RUA DOUTOR AGLIBERTO RODRIGUES MOREIRA','670 '),
    array('RUA DOUTOR ALOÍSIO MENEZES','0194'),
    array('RUA DOUTOR AMÉRICO DE OLIVEIRA','0110'),
    array('RUA DOUTOR ARLINDO SODRÉ','0164'),
    array('RUA DOUTOR EURICO DE AGUIAR','709 '),
    array('RUA DOUTOR IVAN RAMOS DE MEDEIROS','0046'),
    array('RUA DOUTOR JOSÉ BENJAMIN COSTA','0351'),
    array('RUA DOUTOR THOMPSON','0349'),
    array('RUA DOUTORA ODETE BRAGA FURTADO','0224'),
    array('RUA DOUTORA ODETTE BRAGA FURTADO','420 '),
    array('RUA DOZE ','0302'),
    array('RUA DR AGLIBERTO RODRIGUES MOREIRA','701 '),
    array('RUA DR DUARTE BRAGA','526 '),
    array('RUA DR HERWAN MODENESE WANDERLEY','401 '),
    array('RUA DR JOÃO CARLOS SOUZA ','532 '),
    array('RUA DUCKLA DE AGUIAR','901 '),
    array('RUA ELZA DE JESUS','629 '),
    array('RUA EMIDIO COSTA DE SANTANA','527 '),
    array('RUA EMÍLIO FERREIRA SILVA','0017'),
    array('RUA ENG. PINTO HOMEM AZEVEDO','0404'),
    array('RUA ENGENHEIRO CÉSAR DANTAS ','672 '),
    array('RUA ENGENHEIRO FÁBIO RUSCHI ','660 '),
    array('RUA ENGENHEIRO MANOEL DOS PASSOS BARROS','0001'),
    array('RUA ENGENHEIRO RUBENS BLEY','0169'),
    array('RUA EPIFANIO RIBEIRO','499 '),
    array('RUA ERILDO COSTA MATTOS','0175'),
    array('RUA ERNESTO BASSINI','413 '),
    array('RUA EUGENILIO RAMOS','0010'),
    array('RUA EUGÊNIO GUIMARÃES','0313'),
    array('RUA EUGÊNIO NETTO','0282'),
    array('RUA EUGÊNIO RAMOS','0212'),
    array('RUA EUMENES PEIXOTO','536 '),
    array('RUA EURICO DE AGUIAR','0171'),
    array('RUA EZIDIO SILVA','0314'),
    array('RUA FABIANO BISPO SILVA','518 '),
    array('RUA FELICIDADE CORREIA DOS SANTOS','389 '),
    array('RUA FERREIRA COELHO','0229'),
    array('RUA FERREIRA NEVES','522 '),
    array('RUA FILOGÔNIO MOTTA','0268'),
    array('RUA FILOMENO RIBEIRO','0338'),
    array('RUA FLAMBOYANS','337 '),
    array('RUA FLAVIO ABAURRE','0400'),
    array('RUA FLOR  LÍRIO','618 '),
    array('RUA FORTUNATO ABREU GAGNO','0269'),
    array('RUA FORTUNATO RAMOS','0281'),
    array('RUA FRANCISCO DE ALVARENGA RABELO','386 '),
    array('RUA FRANCISCO FUNDÃO','0305'),
    array('RUA FREDERICO GOMES','801 '),
    array('RUA FREDERICO OZANAN','0128'),
    array('RUA FREDERICO PRETTI','807 '),
    array('RUA FREI ANTÔNIO DOS MÁRTIRES','995 '),
    array('RUA GABRIEL ELIAS TAKCLA','520 '),
    array('RUA GASTÃO PACHE FARIAS','0397'),
    array('RUA GASTÃO VILLAR','0191'),
    array('RUA GENERAL CALMON','0271'),
    array('RUA GENERAL OSÓRIO','0108'),
    array('RUA GETÚLIO MIRANDA','675 '),
    array('RUA GILSON MENDONÇA','508 '),
    array('RUA GONÇALVES LEDO','0158'),
    array('RUA GOVERNADOR JOSÉ SETE','0391'),
    array('RUA GRACIANO NEVES','0337'),
    array('RUA GUIDO PRATTI','2304'),
    array('RUA GUILHERME BASSINI','703 '),
    array('RUA GUILHERME MEYER','0185'),
    array('RUA GUILHERME SERRANO','0082'),
    array('RUA HELENA MÜLLER','0176'),
    array('RUA HENRIQUE COUTINHO','0703'),
    array('RUA HENRIQUE MARTINS TUCHE','0297'),
    array('RUA HENRIQUE NOVAES','0114'),
    array('RUA HERCÍLIA DIAS MACIEL','0005'),
    array('RUA HERMES CURRY CARNEIRO','0178'),
    array('RUA HERWAM MEDENEZI','600 '),
    array('RUA HORÁCIO DIAS DOS SANTOS','717 '),
    array('RUA HUMBERTO MARTINS DE PAULA','0362'),
    array('RUA ILMA ANCCHINI ZUMACK','650 '),
    array('RUA ITABIRA','0247'),
    array('RUA ITALINA PEREIRA MOTTA','0243'),
    array('RUA JACOMO FORZA','498 '),
    array('RUA JAIR ANDRADE','0343'),
    array('RUA JOANA MAEIRA FILHA','803 '),
    array('RUA JOÃO  PEREIRA  COSTA','0405'),
    array('RUA JOÃO BASTOS VIEIRA','1011'),
    array('RUA JOÃO BATISTA MARINHO','0311'),
    array('RUA JOÃO BATISTA PARRA','0226'),
    array('RUA JOÃO CARLOS SOUZA','0076'),
    array('RUA JOÃO DA CRUZ','0327'),
    array('RUA JOÃO JOSÉ CABAS','705 '),
    array('RUA JOÃO SOARES','0348'),
    array('RUA JOAQUIM LIRIO','606 '),
    array('RUA JOAQUIM PLÁCIDO DA SILVA','2711'),
    array('RUA JOCA PEREIRA DOS SANTOS','627 '),
    array('RUA JOLINDO GAGNO','706 '),
    array('RUA JONAEL SÓCRATES MEDEIROS FERREIRA','710 '),
    array('RUA JORGE ROSA','681 '),
    array('RUA JOSÉ ALEXANDRE BUAIZ','0498'),
    array('RUA JOSE ANCHIETA FONTANA','0388'),
    array('RUA JOSE BARROSO','0312'),
    array('RUA JOSÉ BITTENCOURT','0011'),
    array('RUA JOSÉ BONIFÁCIO','0702'),
    array('RUA JOSÉ CAETANO SILVA','0392'),
    array('RUA JOSÉ CARVALHO','2203'),
    array('RUA JOSÉ CASSIANO DOS SANTOS','0174'),
    array('RUA JOSÉ CELSO CLÁUDIO','0244'),
    array('RUA JOSÉ COELHO','0236'),
    array('RUA JOSÉ DANIEL NUNES','690 '),
    array('RUA JOSÉ ELIAS DOS REIS FRAGA','0193'),
    array('RUA JOSÉ FARIAS','0277'),
    array('RUA JOSE MACHADO','500 '),
    array('RUA JOSÉ MALTA','0115'),
    array('RUA JOSE MARTINS SILVA','0393'),
    array('RUA JOSÉ MOTTA FRAGA','0274'),
    array('RUA JOSÉ NEVES CYPRESTES','0206'),
    array('RUA JOSÉ ROSA','407 '),
    array('RUA JOSÉ SETTE','516 '),
    array('RUA JOSÉ TEIXEIRA','0276'),
    array('RUA JOSÉ VIVACQUA','671 '),
    array('RUA JOSUÉ PRADO','0336'),
    array('RUA JUDITE LEÃO CASTELO','0270'),
    array('RUA KLEBER JOSÉ DE ANDRADE','103 '),
    array('RUA LAURO CUNHA FREIRE','0179'),
    array('RUA LAURO FARIAS DOS SANTOS','0401'),
    array('RUA LAURO PEREIRA COIMBRA','521 '),
    array('RUA LAURY TAVARES','383 '),
    array('RUA LEA','540 '),
    array('RUA LEÔNCIO NUNES','412 '),
    array('RUA LEOPOLDO NUNES DO AMARAL PEREIRA','0156'),
    array('RUA LOREN RENO','0704'),
    array('RUA LOUREIRO NUNES','667 '),
    array('RUA LUCIDATO VIEIRA FALCÃO','691 '),
    array('RUA LUIZ GOMES TAVARES','529 '),
    array('RUA LUSMAR MACHADO DE MORAES','713 '),
    array('RUA MAJOR OSVALDO CÂNDIDO NUNES','686 '),
    array('RUA MANOEL MESSIAS DOS SANTOS','802 '),
    array('RUA MANOEL PINHEIRO','100 '),
    array('RUA MANOEL SALUSTIANO DE SOUZA','384 '),
    array('RUA MANOEL VIVACQUA','669 '),
    array('RUA MARCELINO DUARTE','0335'),
    array('RUA MARCOS AZEVEDO','021 '),
    array('RUA MARECHAL FLORIANO','0218'),
    array('RUA MARECHAL HERMES','0219'),
    array('RUA MARIA AUXILIADORA G SALOMÃO','615 '),
    array('RUA MARIA DA PAIXÃO SANTOS','507 '),
    array('RUA MARIA ELEONORA PEREIRA','0213'),
    array('RUA MARÍLIA RESENDE SCARTON COUTINHO','0263'),
    array('RUA MARINS ALVARINO','0162'),
    array('RUA MARINS ALVINO','302 '),
    array('RUA MARIO ROSENDO','0408'),
    array('RUA MÁRIO TEIXEIRA NASCIMENTO','87  '),
    array('RUA MARTIM CÃO','1616'),
    array('RUA MIGUEL PESSOA','1313'),
    array('RUA MILTON BASTOS','0307'),
    array('RUA MILTON DE CASTRO MATTOS','0295'),
    array('RUA MILTON MANOEL DOS SANTOS','8848'),
    array('RUA MIOSÓSTES','028 '),
    array('RUA MONSENHOR PEDRINHA','0360'),
    array('RUA MUNIR HILAL','808 '),
    array('RUA NAIR AZEVEDO SILVA','2412'),
    array('RUA NESTOR GOMES','0306'),
    array('RUA NESTOR LIMA','816 '),
    array('RUA NICANOR ALVES DOS SANTOS','708 '),
    array('RUA NOSSA SENHORA D AJUDA','1215'),
    array('RUA NOSSA SENHORA DA CONCEIÇÃO','609 '),
    array('RUA NOVA ESPERANÇA','682 '),
    array('RUA NOVO HORIZONTE','0316'),
    array('RUA NOVO IMPÉRIO','0002'),
    array('RUA NUNES LOURDES','0399'),
    array('RUA ODETE OLIVEIRA LACOURT','0203'),
    array('RUA OITO DE JULHO','0016'),
    array('RUA OLÍMPIO LÍRIO','678 '),
    array('RUA ONZE DE JANEIRO','0196'),
    array('RUA ORLANDO BONFIM','0095'),
    array('RUA ORLANDO ROCHA','0329'),
    array('RUA ORMANDO AGUIAR','0395'),
    array('RUA OSWALDO ARANHA','0309'),
    array('RUA OSWALDO BASTOS DE SOUZA FREITAS','674 '),
    array('RUA OZIAS SARMENTO RODRIGUES','0963'),
    array('RUA PADRE ANTUNES','517 '),
    array('RUA PADRE EMILIO MIOTTI','622 '),
    array('RUA PADRE JOSÉ DE ANCHIETA ','657 '),
    array('RUA PADRE NÓBREGA','0359'),
    array('RUA PAULA MORAES','1414'),
    array('RUA PAULO DE VASCONCELOS','1415'),
    array('RUA PEDESTRE','406 '),
    array('RUA PEDRO CARLOS DE SOUZA','0258'),
    array('RUA PEDRO FONSECA','0326'),
    array('RUA PEDRO LIMA ROSÁRIO','208 '),
    array('RUA PEDRO NOLASCO','327 '),
    array('RUA PEREIRA PINTO','503 '),
    array('RUA PINHEIRO JUNIOR','716 '),
    array('RUA PRESIDENTE ARTHUR BERNARDES','381 '),
    array('RUA PRESIDENTE NEREU RAMOS','534 '),
    array('RUA PRIMAVERA','620 '),
    array('RUA PROCURADOR A. BENEDICTO A. PEREIRA','900 '),
    array('RUA PROF ARNOUD CABRAL','511 '),
    array('RUA PROF BALTAZAR','505 '),
    array('RUA PROF DORALICE OLIVEIRA NEVES','0286'),
    array('RUA PROF FERNANDO DUARTE RABELO','0283'),
    array('RUA PROF FEU ROSA','0013'),
    array('RUA PROF HERÁCLITO PEREIRA','0189'),
    array('RUA PROF ISAURA MARQUES SILVA','0292'),
    array('RUA PROF MARIA ESTELA DE NOVAES','0300'),
    array('RUA PROF MARIA PENHA C ROCHA','535 '),
    array('RUA PROF MARIO F  BORGES','0287'),
    array('RUA PROF O. DRUMOND DE CARVALHO','957 '),
    array('RUA PROF RENATO RIBEIRO SANTOS','0285'),
    array('RUA PROF. OCARLINA DRUMOND DE CARVALHO','651 '),
    array('RUA PROFESSOR JOSÉ NUNES','663 '),
    array('RUA PROFESSOR MAURO FONTOURA BORGES','700 '),
    array('RUA PROFESSORA GLADYS BERNARDO LUCAS','665 '),
    array('RUA PROFESSORA MARIA OCCIOLINA PEREIRA','625 '),
    array('RUA PROFESSORA ODILA SIMÕES','668 '),
    array('RUA PROFESSORA ZILDA ANDRADE','0403'),
    array('RUA PROJETADA','616 '),
    array('RUA QUATRO DE SETEMBRO','1517'),
    array('RUA QUERUBINO COSTA','0373'),
    array('RUA RAFAEL JANTORNO','0007'),
    array('RUA RAUL DE CARVALHO','0319'),
    array('RUA RAUL DE OLIVEIRA NEVES','403 '),
    array('RUA RENATO NASCIMENTO  DAHER CARNEIRO','0264'),
    array('RUA RETORNO PRAÇA DOS NAMORADOS','0233'),
    array('RUA ROBERT EWALD','2409'),
    array('RUA ROBERT KENNEDY','0141'),
    array('RUA ROBERTO SILVEIRA','388 '),
    array('RUA RONALDO  SOARES','0612'),
    array('RUA ROSEMIRO TELLES DE SÁ','0192'),
    array('RUA ROSENDO SERAPIÃO SOUZA FILHO','0301'),
    array('RUA ROSILDA FALCÃO DOS ANJOS','804 '),
    array('RUA RUY DIAS BARBOSA','689 '),
    array('RUA RUY PINTO BANDEIRA','7856'),
    array('RUA SANTA CLARA','102 '),
    array('RUA SANTA RITA DE CÁSSIA','0402'),
    array('RUA SANTO ANTÔNIO','610 '),
    array('RUA SANTOS DUMONT','0165'),
    array('RUA SÃO BARTOLOMEU','0014'),
    array('RUA SÃO BENTO','502 '),
    array('RUA SÃO FRANCISCO','0323'),
    array('RUA SÃO GABRIEL','0188'),
    array('RUA SÃO JOÃO ','0186'),
    array('RUA SÃO JOÃO BATISTA','815 '),
    array('RUA SÃO JORGE','0406'),
    array('RUA SÃO JUDAS TADEU','0322'),
    array('RUA SÃO LAZARO','537 '),
    array('RUA SÃO MARCOS','621 '),
    array('RUA SÃO NICOLAU','712 '),
    array('RUA SÃO PEDRO','0235'),
    array('RUA SÃO SEBASTIÃO','0257'),
    array('RUA SÃO SIMÃO','0350'),
    array('RUA SAUL NAVARRO','0280'),
    array('RUA SEBASTIÃO COSTA','528 '),
    array('RUA SEBASTIÃO PEROVANO','626 '),
    array('RUA SEBASTIÃO TOURINO','0272'),
    array('RUA SÉRGIO NASSER ','695 '),
    array('RUA SERTORIO FRANCO','601 '),
    array('RUA SERVIDÃO','0231'),
    array('RUA SETE DE SETEMBRO','0341'),
    array('RUA SOLDADO BENONI FALCÃO GOUVÊA','944 '),
    array('RUA SOLDADO MANOEL FURTADO','0131'),
    array('RUA SOLON BORGES','699 '),
    array('RUA SOTERO SANTANA','0184'),
    array('RUA TACIANO ABAURRE','524 '),
    array('RUA TAINHA','0021'),
    array('RUA TAL','1483'),
    array('RUA TANCREDO NEVES','0315'),
    array('RUA TENENTE MARIO F BORGES','0390'),
    array('RUA TENENTE MÁRIO FRANCISCO DE BRITO','0232'),
    array('RUA TENENTE SETUBAL','612 '),
    array('RUA TEÓFILO COSTA','408 '),
    array('RUA TREZE DE MAIO','506 '),
    array('RUA TUBARÃO','533 '),
    array('RUA VASCO COUTINHO','0386'),
    array('RUA VICENTE SILVA','300 '),
    array('RUA VICTORINO CARDOSO','0240'),
    array('RUA VILA LOBOS','604 '),
    array('RUA VINTE E TRÊS DE MAIO','0182'),
    array('RUA VITALINO DOS SANTOS VALADARES','531 '),
    array('RUA VITOR FINAMORE','0346'),
    array('RUA VITÓRIO NUNES DA MOTTA','0230'),
    array('RUA WALDIR JUNGER PEREIRA','623 '),
    array('RUA WALDIR MEIRELES','512 '),
    array('RUA WASHINGTON PESSOA','0701'),
    array('RUA ZERMÍNIO OLIVEIRA','0259')
);
$OtrArray = array(
    array('CARLOS ORLANDO CARVALHO','0023'),
    array('FAESA CAMPUS II','2467'),
    array('LADEIRA DOUTOR BEZERRA DE MENEZES','4789'),
    array('LADEIRA MANUEL MINDELA','0006'),
    array('LADEIRA SÃO BENTO','904 '),
    array('MIRANTE','0394'),
    array('PÇA CORONEL FRANC. PEREIRA DO NASC.','8993'),
    array('PONTE AYRTON SENNA','0321'),
    array('PONTE DA PASSAGEM','0024'),
    array('PONTE EDGAR GOMES FEITOSA','697 '),
    array('PONTE FLORENTINO AVIDOS (PONTE SECA)','26  '),
    array('PONTE GOVERNADOR CARLOS LINDEMBERG','25  '),
    array('PONTE MINISTRO PETRONIO PORTELA','1212'),
    array('PONTE PREF. CECILIANO ABEL DE ALMEIDA','0111'),
    array('RODOVIA NORTE SUL','611 '),
    array('RODOVIA SERAFIM DERENZI','0130'),
    array('RODOVIÁRIA','0133'),
    array('TRE','666 '),
    array('TREVO DA FAESA','630 '),
    array('TREVO DA RODOVIÁRIA','0163'),
    array('TREVO DE GOIABEIRAS','538 '),
    array('VIADUTO (RETORNO)','679 '),
    array('VIADUTO DA UFES','574 '),
    array('VIADUTO GILSON FELIX','813 ')
);


/**
 * Funções
 */

// url que exibe as linhas por endereço
define('URL', 'http://sistemas.vitoria.es.gov.br/redeiti/listarLinhas.cfm?cdVia=');

/**
 * Extrai as informações de cada endereço requisitado
 * @param  string $code Código do endereço
 * @return array        Linhas que passam no endereço endereço
 */

function get_lines($code) {
    // define o tempo máximo para processar cada endereço
    set_time_limit(30);
    // faz a requisição do arquivo HTML
    $html = file_get_html(URL . $code);
    // extra os números das linhas
    $lines = array();
    $links = $html->find('.main a[href^=listar]');
    foreach ($links as $line) {
        $code = substr($line->plaintext, 0, 4);        
        $lines[] = $code;
    }
    return $lines;
}

/**
 * Imprime as informações extraídas
 * 
 * @param  array $addressList Lista de endereços
 * @param  string $type       Tipo do endereço
 * @return undefined
 */

function parse_lines_from_list($addressList, $type) {
    echo "\"data\" : {";
    foreach ($addressList as $address) {
        $name = $address[0];
        $code = $address[1];
        // pega as informações do endereço
        $lines = get_lines($address[1]);
        // re-ordena as linhas
        sort($lines);
        // transforma de array PHP para JSON
        $lines = json_encode($lines);
        // monta as propriedades de cada linha
        echo "
        \"${code}\" : {
            \"name\" : \"${name}\",
            \"type\" : \"${type}\",
            \"lines\" : ${lines}
        },";
    }
    echo "\n}";
}
?>
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Linhas por endereço</title>
</head>
<body>
    <h1>Linhas por endereço</h1>
    <pre>
        <code>
    <?php
//      parse_lines_from_list($AvArray, 'avenue');
//      parse_lines_from_list($RuaArray, 'street');
//      parse_lines_from_list($PcArray, 'square');
      parse_lines_from_list($OtrArray, 'other');
    ?>
        </code>
    </pre>
</body>
</html>
